spring:
  application:
    name: BankApp
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_app_db?currentSchema=bank
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
logging:
  file:
    name: logs/bankapp.log
security:
  jwt:
    key:
      private: 98ba36905941c30d4fe13c7a84c2d91f1c02384f003e188ee601d4da76f22058
    user:
      generator: AUTH0JWT-BACKEND
#app:
#  cors:
#    allowed-origins: *
