spring:
  application:
    name: BankApp
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_app_db?currentSchema=bank
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
logging:
  file:
    name: logs/bankapp.log
